version: '3'
networks:
  zk-net:
    name: zk-net
services:
  zk1:
    # docker container所使用的docker image
    image: zookeeper
    hostname: zk1
    container_name: zk1
    # 配置docker container和宿主机的端口映射
    ports:
      - 2181:2181
      - 8081:8080
    # 配置docker container的环境变量
    environment:
      # 当前zk实例的id
      ZOO_MY_ID: 1
      # 整个zk集群的机器、端口列表
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    # 将docker container上的路径挂载到宿主机上 实现宿主机和docker container的数据共享
    volumes:
      - /home/zookeeper/zk1/data:/data
      - /home/zookeeper/zk1/datalog:/datalog
    # 当前docker container加入名为zk-net的隔离网络
    networks:
      - zk-net

  zk2:
    image: zookeeper
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - /home/zookeeper/zk2/data:/data
      - /home/zookeeper/zk2/datalog:/datalog
    networks:
      - zk-net

  zk3:
    image: zookeeper
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
      - 8083:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - /home/zookeeper/zk3/data:/data
      - /home/zookeeper/zk3/datalog:/datalog
    networks:
      - zk-net



  redis:
    image: redis:6
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /home/redis/data:/data #数据文件挂载
      - /home/redis/logs:/logs
      - /home/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/my.conf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
      - ./mysql/data:/data/mysqldata
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
#     - "MYSQL_DATABASE=test"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306